apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: d-web
spec:
  replicas: 5
  template:
    metadata:
      labels:
        web: rails
    spec:
      containers:
      - name: web
        image: eongsioco/popcorn:5
        ports:
        - containerPort: 3333